#repos:
#  - repo: https://github.com/psf/black
#    # PEP8 autoformat (spaces, ...)
#    rev: 23.3.0
#    hooks:
#      - id: black
#  - repo: https://github.com/PyCQA/isort
#    # PEP8 imports
#    rev: 5.12.0
#    hooks:
#      - id: isort
#  - repo: https://github.com/PyCQA/flake8
#    # Others (e.g. unused import or undefined name)
#    rev: 6.0.0
#    hooks:
#      - id: flake8